"""Add guests and reservations tables

Revises: 63f01d56e28e
Revises: eb44ed6fb1d9
Create Date: 2026-02-14 22:51:34.163959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b9b03a65576'
down_revision: Union[str, None] = '63f01d56e28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=True),
    sa.Column('document_number', sa.String(length=60), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=180), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', name='reservationstatus'), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('check_out_date > check_in_date', name='check_dates'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_amenity_map',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('amenity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['room_amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('card', 'wallet', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'authorized', 'paid', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('provider_txn_id', sa.String(length=120), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=30), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
   


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_inventory',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('room_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'available'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('floor >= 1 AND floor <= 10', name=op.f('room_inventory_floor_check')),
    sa.ForeignKeyConstraint(['room_type_id'], ['rooms.id'], name=op.f('room_inventory_room_type_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('room_inventory_pkey')),
    sa.UniqueConstraint('room_number', name=op.f('room_inventory_room_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('payments')
    op.drop_table('room_amenity_map')
    op.drop_table('reservations')
    op.drop_table('room_amenities')
    op.drop_table('guests')
    # ### end Alembic commands ###
